#!/usr/bin/python

VERSION="0.11"

#from Tkinter import *
import tkMessageBox
import Tkinter
import ttk
import platform
from avc_finder.finder import *

top = Tkinter.Tk()
top.title("AVerCaster Finder v" + VERSION)
w = 420
h = 450
# get screen width and height
ws = top.winfo_screenwidth() # width of the screen
hs = top.winfo_screenheight() # height of the screen
# calculate x and y coordinates for the Tk top window
x = (ws/2) - (w/2)
y = (hs/2) - (h/2)
# set the dimensions of the screen 
# and where it is placed
top.geometry('%dx%d+%d+%d' % (w, h, x, y))
top.lift()

# bring window to front
if platform.system() != 'Darwin':
    top.lift()
    top.call('wm', 'attributes', '.', '-topmost', True)
    top.after_idle(top.call, 'wm', 'attributes', '.', '-topmost', False)
else:
    import os
    from Cocoa import NSRunningApplication, NSApplicationActivateIgnoringOtherApps
    app = NSRunningApplication.runningApplicationWithProcessIdentifier_(os.getpid())
    app.activateWithOptions_(NSApplicationActivateIgnoringOtherApps)

def searchCallBack():

    # clean up all items
#    Lb1.delete(0, Tkinter.END)
    tv.delete(*tv.get_children())

    devices3 = finder3_find_product()

    for ip in devices3:
#        Lb1.insert(Tkinter.END, devices3[ip]['model'] + " " + ip + " " + 
#              devices3[ip]['mac1'] + " " + devices3[ip]['version'])
        tv.insert("", "end", devices3[ip]['mac1'], text=devices3[ip]['model'], 
                values=(ip, devices3[ip]['mac1'], devices3[ip]['version']
                   ))
        print "Add:", devices3[ip]['model'], ip, devices3[ip]['mac1'], devices3[ip]['version']


#    devices2 = finder2_find_product()

#    for ip in devices2:
#        Lb1.insert(Tkinter.END, devices2[ip]['model'] + " " + ip + " " + 
#              devices2[ip]['mac1'] + " " + devices2[ip]['version'])
#        tv.insert("", "end", devices2[ip]['mac1'], text=devices2[ip]['model'], 
#                values=(ip, devices2[ip]['mac1'], devices2[ip]['version']
#                    ))
#        print "Add:", devices2[ip]['model'], ip, devices2[ip]['mac1'], devices2[ip]['version']

B = Tkinter.Button(top, text ="Search", command = searchCallBack)
B.pack()

#Lb1 = Tkinter.Listbox(top)
#Lb1.insert(1, "Click \"Search\" to find AVerCaster products on LAN")

#Lb1.pack(fill=BOTH)
#Lb1.pack(expand=1,  fill=Tkinter.BOTH)

tv = ttk.Treeview(top)
tv["columns"] = ("IP", "MAC", "Firmware version")
tv.heading("#0", text="Model")
tv.column("#0", anchor="w", width=70)

tv.heading("IP", text="IP")
tv.column("IP", anchor="w", width=100)

tv.heading("MAC", text="MAC")
tv.column("MAC", anchor="w", width=150)

tv.heading("Firmware version", text="F/W version")
tv.column("Firmware version", anchor="w", width=100)

tv.pack(expand=1, fill=Tkinter.BOTH)

top.mainloop()

